image:
  repository: tccr.io/truecharts/ubooquity
  pullPolicy: IfNotPresent
  tag: v2.1.3

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 2202
        port: 2202
  admin:
    enabled: true
    ports:
      admin:
        enabled: true
        port: 2203
        targetPort: 2203 
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
